### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by benlk** [INN/maine-legislature#77]
This issue is just a note for future reference.

---

The following UnicodeDecodeError is caused by smart quotes in the spreadsheet. Replace curly double quotes with `&#34;` quotation marks and curly single quotes with `&#39;` apostrophes.

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 254: ordinal not in range(128)

```
Traceback (most recent call last):
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/blk/inn/maine-legislature/app.py", line 39, in index
    return make_response(render_template('index.html', **context))
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/templating.py", line 125, in render_template
    context, ctx.app)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/flask/templating.py", line 107, in _render
    rv = template.render(context)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/blk/inn/maine-legislature/templates/index.html", line 1, in top-level template code
    {% extends '_base.html' %}
  File "/Users/blk/inn/maine-legislature/templates/_base.html", line 30, in top-level template code
    {% block outer_content %}
  File "/Users/blk/inn/maine-legislature/templates/_base.html", line 42, in block "outer_content"
    {% block header_content %}
  File "/Users/blk/inn/maine-legislature/templates/index.html", line 4, in block "header_content"
    {% include '_maine_legislature_header.html' %}
  File "/Users/blk/inn/maine-legislature/templates/_maine_legislature_header.html", line 12, in top-level template code
    <div class="story-description">{{ COPY.content.project_description|smarty }}</div>
  File "/Users/blk/inn/maine-legislature/render_utils.py", line 224, in smarty_filter
    return Markup(s)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/markupsafe/__init__.py", line 74, in __new__
    return text_type.__new__(cls, base)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 254: ordinal not in range(128)
```

**Comment by benlk** [comment]
Reopening with `u'\xe9'`: an `é` in the name of a business. 

```
Traceback (most recent call last):
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/blk/.virtualenvs/maine-legislature/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/blk/inn/maine-legislature/fabfile/render.py", line 141, in render_all
    content = view().data
  File "/Users/blk/inn/maine-legislature/app.py", line 55, in legislator
    context['family'] = get_legislator_family_by_slug(slug)
  File "/Users/blk/inn/maine-legislature/helpers.py", line 245, in get_legislator_family_by_slug
    if str(row['Family_Member_Employers_Name']) != '':
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
```
